## Programmed by WW
##           20.04.2010.  WW	


# Project name
IF(NOT OGS_USE_QT)
	PROJECT( OGS-FEM-${OGS_VERSION_MAJOR}-${PRJ_EXT} )
ENDIF(NOT OGS_USE_QT)


# Find OpenMP
IF(PARALLEL_USE_OPENMP)
	FIND_PACKAGE( OpenMP )
 
## Might be needed 
#	IF (MSVC)
#		SET(CMAKE_CXX_FLAGS_DEBUG "USE_OPENMP" /openmp)
#		SET(CMAKE_CXX_FLAGS_RELEASE "USE_OPENMP" /openmp)
#	ENDIF(MSVC)

#	IF(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_GNUCC)
#		add_definitions(
#			-O3 
#			-fopenmp 
#			-lpthread 
#		)
#	ENDIF(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_GNUCC)

	IF(OPENMP_FOUND)
		SET( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}" )	
	ENDIF(OPENMP_FOUND)
ENDIF(PARALLEL_USE_OPENMP)

IF(PARALLEL_USE_MPI)
	IF (WIN32)
		MESSAGE (FATAL_ERROR "Aborting: MPI is only supported under UNIX/LINUX!")
#		FIND_PACKAGE(MPI)
#		IF(MPI_FOUND)		
##			SET(CMAKE_C_COMPILER mpicc)
##			SET(CMAKE_CXX_COMPILER mpicxx)
#		ELSE(MPI_FOUND)
#			MESSAGE (FATAL_ERROR "Aborting: MPI implementation is not found!")
#		ENDIF(MPI_FOUND)			
	ENDIF(WIN32)
	IF(UNIX)
		FIND_PACKAGE(MPI)
		IF(MPI_FOUND)		
			SET(CMAKE_C_COMPILER ${MPI_COMPILER})
			SET(CMAKE_CXX_COMPILER ${MPI_COMPILER})
			ADD_DEFINITIONS(-DNEW_EQS -DUSE_MPI)    			
		ELSE(MPI_FOUND)
			MESSAGE (FATAL_ERROR "Aborting: MPI implementation is not found!")
		ENDIF(MPI_FOUND)			
	ENDIF(UNIX)
	
ENDIF(PARALLEL_USE_MPI)


IF(OGS_USE_QT OR OGS_FEM_GEMS OR OGS_FEM_BRNS OR OGS_FEM_MKL OR  OGS_FEM_PQC OR OGS_FEM_LIS)
	include_directories( ${CMAKE_SOURCE_DIR}/LIB )
	link_directories( ${CMAKE_SOURCE_DIR}/LIB )
ENDIF(OGS_USE_QT OR OGS_FEM_GEMS OR OGS_FEM_BRNS OR OGS_FEM_MKL OR  OGS_FEM_PQC OR OGS_FEM_LIS)


# Add subdirectories with the projects
ADD_SUBDIRECTORY( Base )
ADD_SUBDIRECTORY( MathLib )
ADD_SUBDIRECTORY( GEO )
ADD_SUBDIRECTORY( MSH )
ADD_SUBDIRECTORY( FEM )
IF(OGS_FEM_GEMS)
	ADD_SUBDIRECTORY( GEM )
ENDIF(OGS_FEM_GEMS)
ADD_SUBDIRECTORY( FileIO )
ADD_SUBDIRECTORY( OGSProject )
ADD_SUBDIRECTORY( OGS )
