ROOTINCLUDE=../
FEMINCLUDE=../FEM
GEOINCLUDE=../GEO
MSHINCLUDE=../MSH
GEN_INCLUDES = -I$(ROOTINCLUDE) -I$(FEMINCLUDE) -I$(GEOINCLUDE) -I$(MSHINCLUDE)  

OPTFLAG =  -O3 -fno-nonansi-builtins -DGCC
DEBFLAG = #-ggdb
WARN = -Wall


C++ = g++ -c $(WARN) -pedantic $(GEN_INCLUDES) $(OPTFLAG) $(DEBFLAG) -D_POSIX_SOURCE -DNO_ERROR_CONTROL
