# GeoSys - Makefile for LINUX
# Last modification 04/11/2004 WW

ROOTINCLUDE=../
FEMINCLUDE=../FEM
GEOINCLUDE=../GEO
MSHINCLUDE=../MSH
GEN_INCLUDES = -I$(ROOTINCLUDE) -I$(FEMINCLUDE) -I$(GEOINCLUDE) -I$(MSHINCLUDE) 
OPTFLAG = -K rtti
DEBFLAG = #-ggdb
WARN = 

C++ = sxc++ -c $(WARN) $(GEN_INCLUDES) $(OPTFLAG) $(DEBFLAG) -D_POSIX_SOURCE -DNO_ERROR_CONTROL
