//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GeoSys.rc
//
#define IDC_BUTTON_PCS_READ             2
#define IDC_BUTTON_READ                 2
#define ID_BUTTON_MAT_FP_CALC           3
#define IDCANCEL2                       3
#define IDC_BUTTON_PCS_WRITE            3
#define IDC_BUTTON_READ_IC              3
#define IDC_BUTTON_PCS_OK               4
#define IDC_BUTTON_MOD_READ_M           4
#define IDC_BUTTON_PCS_READ3            5
#define IDC_BUTTON_MOD_READ_T           5
#define IDC_BUTTON_PCS_READ4            6
#define IDD_ABOUTBOX                    100
#define IDD_GSFORMRIGHTPASSIVE          103
#define IDD_OGL_TETRA_VIEW              106
#define IDD_GS_MESH_IMP                 107
#define IDR_MAINFRAME                   128
#define IDR_GEOSYSTYPE                  129
#define IDD_OGLINFO_DIALOG              130
#define IDI_ICON1                       130
#define IDB_TREE_CTRL_OPTIONS           131
#define IDD_DIALOG1                     136
#define IDD_MSH_REFINE                  138
#define IDD_NEWPROJECT                  139
#define IDD_GRAPHICS_COLOR              140
#define IDD_DIALOG_MAT_MECH             141
#define IDD_MAT_SP                      141
#define IDD_MAT_PAD_DLG                 142
#define IDD_TOLERANCE                   142
#define IDD_PRISGEN                     143
#define IDC_ZOOMCURSOR                  146
#define IDD_MAPPING                     146
#define IDD_VerticalDiscretization      147
#define IDC_CURSOR_DRAW                 149
#define IDD_DIALOG2                     150
#define IDD_DIALOG_PLOT                 150
#define IDD_DIALOG_INTERPOLATION        152
#define IDD_DIALOG_IDW                  152
#define IDD_DIALOG_INTERPOLATE          156
#define IDD_DIALOG_KRIGING              157
#define IDD_DIALOG_RBF                  158
#define IDD_DIALOG_LEGEND               159
#define IDD_PCS_DISPLAY_CONTROL         160
#define IDD_OGL_VIEW_CONTROL            161
#define IDD_MAT_GROUP_EDITOR_DATAEDIT   162
#define IDD_PICKEDPROPERTY              163
#define IDD_MESHEXTENSION_DIALOG        164
#define IDD_DIALOG_IC                   165
#define IDD_STRUCTURED_MESH_DIALOG      170
#define IDD_SHP                         171
#define IDD_PTVALUES                    172
#define IDR_MATGROUP_POPUP              172
#define IDD_SOIL                        173
#define IDD_ISO_COL                     174
#define IDD_ISO_VALUE                   175
#define IDD_ISO_FRAMEWIDTH              176
#define IDD_BOUNDARY_CONDITIONS         220
#define IDD_ST                          220
#define IDD_MAT_FP_DENSITY              237
#define IDD_SURFACE                     241
#define IDD_POINT                       242
#define IDD_SOURCE_TERM                 243
#define IDD_OUT_OBSERVATION_POINTS      244
#define IDD_OUT_OBSERVATION_POLYLINES   245
#define IDD_OUT_MAT                     246
#define IDD_DIALOG_GRAPHICS             247
#define IDD_MAT_GROUP_EDITOR            249
#define IDD_SOURCE_TERMS                250
#define IDD_FORM                        250
#define IDD_MSH_EDITOR                  251
#define IDD_DIALOG_TABLE_WELLS          252
#define IDD_PCS                         253
#define IDD_PCS_EDITOR                  253
#define IDD_VOLUME                      255
#define IDD_SIMULATOR                   256
#define IDC_STATIC_VENDOR               1000
#define IDC_MAT_MECH_GRID               1000
#define IDC_STATIC_RENDERER             1001
#define IDC_STATIC_VERSION              1002
#define IDC_BUTTON_EDIT                 1002
#define IDC_LIST_QUANTITIES             1002
#define IDC_STATIC_ACCELERATION         1003
#define IDC_BUTTON_ADD                  1003
#define IDC_LIST_QUANTITIES2            1003
#define IDC_STATIC_EXTENSIONS           1004
#define IDC_RADIO_TYPE                  1004
#define IDC_BUTTON_WRITE                1004
#define IDC_STATIC_GLUEXTENSIONS        1005
#define IDC_RADIO_TYPE2                 1005
#define IDC_STATIC_GLUVERSION           1006
#define IDC_RADIO_TYPE3                 1006
#define IDC_RADIO_TYPE4                 1007
#define IDC_EDIT_1                      1008
#define IDC_EDIT_2                      1009
#define IDC_DETAILS_BUT                 1010
#define IDC_EDIT_3                      1010
#define IDC_GIF                         1011
#define IDC_EDIT_4                      1011
#define IDC_MODEL_LIST                  1012
#define IDC_EDIT_5                      1012
#define IDC_GEO_INFO                    1012
#define IDC_EDIT_6                      1013
#define IDC_EDIT_7                      1014
#define IDC_EDIT_8                      1015
#define IDC_LIST                        1016
#define IDC_BUTTON_UPDATE               1017
#define IDC_BUTTON_IC_UPDATE            1017
#define IDC_BUTTON_REMOVE               1018
#define IDC_BUTTON_SelectALL            1018
#define IDC_BUTTON_REMOVEALL            1019
#define IDC_BUTTON_SelectNone           1019
#define IDC_RADIO_VALUE                 1020
#define IDC_BUTTON_PLY2SFC              1020
#define IDC_RADIO_DIST_TYPE1            1020
#define IDC_BUTTON_APPLY                1021
#define IDC_LIST_SURFACES               1021
#define IDC_EDIT_PRISGEN1               1022
#define IDC_EDIT_POINT_2                1022
#define IDC_BUTTON_SURFACE_ADD          1022
#define IDC_RADIO_GEO_TYPE5             1022
#define IDC_EDIT_PRISGEN2               1023
#define IDC_EDIT_POINT_3                1023
#define IDC_BUTTON_SURFACE_UPDATE       1023
#define IDC_EDIT_9                      1023
#define IDC_BUTTON_CREATEPRISMS         1024
#define IDC_EDIT_POINT_4                1024
#define IDC_BUTTON_SURFACE_REMOVE       1024
#define IDC_BUTTON_ANALYZERFI           1025
#define IDC_EDIT_POINT_1                1025
#define IDC_BUTTON_SURFACE_REMOVEALL    1025
#define IDC_BUTTON_MSH_EXECUTE          1025
#define IDC_BUTTON_CREATE_PRISM_ELEMENTS 1025
#define IDC_EDIT_PRISGENMESSAGE         1026
#define IDC_BUTTON_POINT_ADD            1026
#define IDC_LIST_SURFACE_POLYLINES      1026
#define IDC_BUTTON_MSH_ACTIVATE         1026
#define IDC_EDIT_MAT_GROUP              1026
#define IDC_BUTTON_MSH_EXECUTE2         1026
#define IDC_CHECK_PROCESS_T             1027
#define IDC_BUTTON_POINT_UPDATE         1027
#define IDC_BUTTON_SURFACE_REMOVE3      1027
#define IDC_BUTTON_SURFACE_CREATE_TIN   1027
#define IDC_BUTTON_GEO_NODES            1027
#define IDC_BUTTON_CREATE_PRISM_ELEMENTS2 1027
#define IDC_CHECK_PROCESS_C             1028
#define IDC_BUTTON_POINT_REMOVE         1028
#define IDC_EDIT_SURFACE_NAME           1028
#define ID_DELETE_DOUBLE                1028
#define IDC_BUTTON_MSH_DELETE           1028
#define IDC_BUTTON_PRISM_REFINE         1028
#define IDC_CHECK51                     1029
#define IDC_BUTTON_POINT_REMOVEALL      1029
#define IDC_RADIO_SURFACE_TYPE1         1029
#define IDC_CHECK_PROCESS_M             1029
#define IDC_EDIT_PRISGEN_REFINE         1029
#define IDC_BUTTON_LAYER_POLYLINES      1029
#define IDC_MapRow                      1030
#define IDC_RADIO_SURFACE_TYPE2         1030
#define IDC_BUTTON_POINT_UPDATE2        1030
#define IDC_EDIT_PRISGEN_ELEMENTS       1030
#define IDC_BUTTON_LAYER_SURFACES       1030
#define IDC_RowNumber                   1031
#define IDC_RADIO_SURFACE_TYPE3         1031
#define IDC_BUTTON_POINT_REMOVE_DOUBLEPOINTS 1031
#define IDC_BUTTON_EDGE_LENGTH          1031
#define IDC_RADIO_SURFACE_TYPE4         1032
#define IDC_BUTTON_POINT_NO_HIGHLIGHT   1032
#define IDC_CountOfPrismLayers          1033
#define IDC_COMBO_BC_SURFACES           1033
#define IDC_PNT_RADIO1                  1033
#define IDC_COMBO_GEO_TYPE              1033
#define IDC_RADIO_SURFACE_TYPE5         1033
#define IDC_PNT_RADIO2                  1034
#define IDC_CHECK_DISPLAY_IC            1034
#define IDC_CMD_BROWSE                  1034
#define IDC_COMBO_DIS_TYPE              1034
#define IDC_RADIO_SURFACE_TYPE6         1034
#define IDC_EDIT_POINT_5                1035
#define IDC_CHECK_DISPLAY_BC            1035
#define IDC_LIST_ST_QUANTITIES          1035
#define IDC_TXT_FOLDERPATH              1035
#define IDC_COMBO_PCS_NUMBER            1035
#define IDC_BUTTON_SFC2MAP              1035
#define IDC_RefineLayer                 1036
#define IDC_EDIT_POINT_6                1036
#define IDC_CHECK_DISPLAY_PLY           1036
#define IDC_LIST_ST_PROPERTIES          1036
#define IDC_PROJECT_NAME                1036
#define IDC_COMBO_MAT_GROUP             1036
#define IDC_EDIT_SURFACE_MAP_FILE       1036
#define IDC_COMBO_TIM_TYPE              1036
#define IDC_BUTTON_POINT_PROPERTIES_UPDATE 1037
#define IDC_CHECK_DISPLAY_MSH           1037
#define IDC_BUTTON_FILE                 1037
#define IDC_LayerToBeDiscretized        1038
#define IDC_PNT_RADIO3                  1038
#define IDC_CHECK_DISPLAY_PNT           1038
#define IDC_RADIO_ST_DIS_TYPE1          1038
#define IDC_BUTTON_SURFACE_WRITE_TEC    1038
#define IDC_NumberOfSublayers           1039
#define IDC_LIST_POINTS                 1039
#define IDC_CHECK_DISPLAY_ISOLINES      1039
#define IDC_LIST_ST_POLYLINES           1039
#define IDC_BUTTON_CREATE_LAYER_TINs    1039
#define IDC_LIST_POINT                  1040
#define IDC_CHECK_DISPLAY_ISOSURFACES   1040
#define IDC_LIST_ST_SURFACES            1040
#define IDC_PNT_RADIO4                  1040
#define IDC_BUTTON_SELECT               1041
#define IDC_COMBO_ST_SURFACES           1041
#define IDC_CHECK_DISPLAY_SUF           1041
#define IDC_BUTTON_UNSELECT             1042
#define IDC_BUTTON_ST_ADD               1042
#define IDC_CHECK_DISPLAY_MSH_LINE      1042
#define IDC_RADIO_ST_GEO_TYPE1          1043
#define IDC_CHECK_DISPLAY_MSH_TRI       1043
#define IDC_EDIT_ST_VALUE               1044
#define IDC_CHECK_DISPLAY_TINs          1044
#define IDC_CHECK_MSH_ACTIVATE_LINE     1044
#define IDC_BUTTON1                     1045
#define IDC_GRID_BUTTON                 1045
#define IDC_CHECK_DISPLAY_VOL           1045
#define IDC_CHECK_MSH_ACTIVATE_TRI      1045
#define IDC_GRID_REMOVE_BUTTON          1045
#define IDC_RADIO_MSH_REFINE1           1046
#define IDC_EDIT_SURFACE_7              1046
#define IDC_BUTTON_WRITE_MP             1046
#define IDC_CHECK_DISPLAY_MSH_QUAD      1046
#define IDC_DELETEALL                   1046
#define IDC_BUTTON_FCT_WRITE            1046
#define IDC_BUTTON9                     1046
#define IDC_BUTTON_NUM                  1046
#define IDC_CHECK_DISPLAY_MSH_TET       1047
#define IDC_BUTTON3                     1047
#define IDC_BUTTON_WRITE_MP2            1047
#define IDC_BUTTON_READ_MFP             1047
#define IDC_CREATE_FIELDS               1047
#define IDC_EDIT_MSH_REFINE1            1048
#define IDC_CHECK_DISPLAY_MSH_PRIS      1048
#define IDC_EXPORT                      1048
#define IDC_BUTTON10                    1048
#define IDC_BUTTON_OUT                  1048
#define IDC_LIST_OBSERVATION_POINTS     1049
#define IDC_RADIO_IC_DIST_TYPE2         1049
#define IDC_CHECK_LABELS                1049
#define IDC_CHECK_DISPLAY_MSH_HEX       1049
#define IDC_SHOW_PNT_LABELS             1049
#define IDC_BUTTON11                    1049
#define IDC_BUTTON_IC                   1049
#define IDC_CHECK_DISPLAY_PLY_PNT       1050
#define IDC_CHECK_MSH_ACTIVATE_QUAD     1050
#define IDC_BUTTON12                    1050
#define IDC_BUTTON_BC                   1050
#define IDC_LIST_OBSERVATION_POLYLINES  1051
#define IDC_LIST_OUT_POLYLINES          1051
#define IDC_CHECK_DISPLAY_PLY_LIN       1051
#define IDC_CHECK_MSH_ACTIVATE_TET      1051
#define IDC_BUTTON13                    1051
#define IDC_BUTTON_ST                   1051
#define IDC_LIST_MAT_PROPERTIES         1052
#define IDC_CHECK_DISPLAY_NOD           1052
#define IDC_BUTTON14                    1052
#define IDC_BUTTON_MFP                  1052
#define ID_ADD_OBSERVATION_POINT        1053
#define IDC_CHECK_DISPLAY_ELE_DOUBLE    1053
#define IDC_BUTTON15                    1053
#define IDC_BUTTON_MSP                  1053
#define IDC_BUTTON_ST_REMOVE            1054
#define IDC_CHECK_DISPLAY_MAT_GROUPS    1054
#define IDC_CHECK_DISPLAY_LABELS        1054
#define IDC_BUTTON16                    1054
#define IDC_BUTTON_MCP                  1054
#define IDC_BUTTON_ST_REMOVEALL         1055
#define IDC_CHECK_DISPLAY_ST            1055
#define IDC_CHECK_MSH_ACTIVATE_PRIS     1055
#define ID_REMOVE_TIME_STEPS            1055
#define ID_ADD_NOD_VALUE                1055
#define IDC_BUTTON17                    1055
#define IDC_BUTTON_MMP                  1055
#define IDC_RADIO1                      1056
#define IDC_CHECK_MSH_ACTIVATE_HEX      1056
#define IDC_BUTTON_SELECT_ALL           1056
#define IDC_BUTTON_OBJ                  1056
#define IDC_RADIO2                      1057
#define IDC_BUTTON_UNSELECT2            1057
#define IDC_BUTTON_SELECT_NONE          1057
#define IDC_BUTTON_NOD                  1057
#define IDC_BUTTON_MOD_CHECK            1057
#define IDC_LIST_POLYLINES_GEO          1058
#define IDC_CHECK_DISPLAY_MAT_GROUPS2   1058
#define IDC_CHECK_DISPLAY_ObS_WELLS     1058
#define ID_ADD_ELE_VALUE                1058
#define IDC_BUTTON_ELE                  1058
#define IDC_BUTTON_MOD_READ             1058
#define IDC_LIST_POLYLINES_MSH          1059
#define IDC_CHECK_DISPLAY_ObS_WELLS2    1059
#define IDC_CHECK_AXIS                  1059
#define ID_VAL_CLEAR                    1059
#define IDC_BUTTON_UPDATE_TREE          1059
#define IDC_BUTTON_GEO2MSH              1060
#define IDC_BUTTON_SELECT_ALL2          1060
#define ID_VAL_ELE_CLEAR                1060
#define IDC_BUTTON_MOD_EDITOR           1060
#define IDC_LIST_MAT_DB                 1061
#define IDC_LIST_GEOMETRY               1061
#define IDC_RADIO3                      1061
#define IDC_BUTTON_SELECT_NONE2         1061
#define IDC_BUTTON_NEW_MATGROUP         1061
#define IDC_LIST_MAT_GROUPS             1062
#define IDC_BUTTON_SELECT_ALL3          1062
#define IDC_BUTTON_GEO2MSH2             1062
#define IDC_BUTTON_CREATE_MSP           1062
#define IDC_LIST_MAT_PLY                1063
#define IDC_BUTTON_SELECT_NONE3         1063
#define IDC_LIST_MAT_SFC                1064
#define IDC_CHECK_LABELS2               1064
#define IDC_SHOW_PLY_LABELS             1064
#define IDC_LIST_MAT_VOL                1065
#define IDC_COMB_GEOMETRY               1065
#define IDC_CHECK_LABELS3               1065
#define IDC_SHOW_SFC_LABELS             1065
#define IDC_BUTTON_MAT_REMOVE           1066
#define IDC_COMBO_LINETYPE              1066
#define IDC_CHECK_LABELS4               1066
#define IDC_SHOW_VOL_LABELS             1066
#define IDC_BUTTON_MAT_UPDATE           1067
#define IDC_CHECK_DISPLAY_MSH_PRIS2     1067
#define IDC_BUTTON_LOAD_MAT_DB          1068
#define IDC_BUTTON_SELECT_ALL4          1068
#define IDC_BUTTON_FCT_INTERPOLATE      1068
#define IDC_COMBO_MAT_PAD               1069
#define IDC_MAT_COMBO_PAD               1069
#define IDC_BUTTON_CALC_MIN_MAX         1069
#define IDC_CUSTOM2                     1070
#define IDC_MAT_PAD_GRID                1070
#define IDC_CHECK_DISPLAY_MSH_LABELS    1070
#define IDC_MAT_GRID_SFC                1071
#define ID_BUTTON_OUT_PLY               1071
#define IDC_CHECK_DISPLAY_BMP           1071
#define IDC_BUTTON_DELETE               1072
#define IDC_BUTTON_DRAW_MSH             1072
#define IDC_CHECK_THERMAL               1073
#define IDC_COMB_LAYER                  1073
#define IDC_CHECK_DISPLAY_MSH_LABELS2   1073
#define IDC_CHECK_DISPLAY_MSH_MAT       1073
#define IDC_CHECK_ELASTICITY            1074
#define IDC_EDIT_TOLERANCE              1074
#define IDC_CHECK_DISPLAY_DOM           1074
#define IDC_CHECK_PLASTICITY            1075
#define IDC_BUTTON_WRITE_DOM_TEC        1075
#define IDC_EDIT_MIN_POLYLENGTH         1075
#define IDC_COMBO_PLASTICITY            1076
#define IDC_EDIT_MIN_QUALITY_VALUE      1076
#define IDC_EDIT_MAX_POLYLENGTH         1076
#define IDC_SHOW_SFC_MAT                1076
#define IDC_STATIC_MAT_MECH1            1077
#define IDC_EDIT_MAX_QUALITY_VALUE      1077
#define IDC_CHECK_DISPLAY_SFC_VALUES    1077
#define IDC_EDIT_SMALER_POLYLENGTH_DEF  1077
#define IDC_STATIC_MAT_MECH2            1078
#define IDC_EDIT_MPA_X                  1078
#define IDC_LIST_FILE                   1079
#define IDC_EDIT_MPA_Y                  1079
#define IDC_BUTTON_ADD_FILE             1080
#define IDC_EDIT_MPA_Z                  1080
#define IDC_BUTTON_EXECUTE              1081
#define IDC_REMESH_BWA                  1081
#define IDC_EDIT1                       1082
#define IDC_BUTTON_CREATE               1082
#define IDC_REMESH_REMOVE_POINT         1082
#define IDC_PROGRESS_MAPPING            1083
#define IDC_EDIT_ANGLE                  1083
#define IDC_EDIT_REMOVE_NR              1083
#define IDC_Y_IMAGEDISTORT              1083
#define IDC_BUTTON_VOL_SFC              1083
#define IDC_PROGRESS_TIN                1084
#define IDC_EDIT_R2                     1084
#define IDC_EDIT_ANGLE_NUGGET           1084
#define IDC_X_IMAGEDISTORT              1084
#define IDC_GRID_BC                     1085
#define IDC_GRID_ST                     1086
#define IDC_CHECK_MSH_ACTIVE            1087
#define IDC_CHECK4                      1090
#define IDC_BUTTON_MAT_CONNECT_LINE     1090
#define IDC_BUTTON_MAT_CONNECT_TRI      1091
#define IDC_CHECK19                     1091
#define IDC_BUTTON_MAT_CONNECT_QUAD     1092
#define IDC_CHECK20                     1092
#define IDC_CHECK5                      1093
#define IDC_BUTTON_MAT_CONNECT_TET      1093
#define IDC_CHECK6                      1094
#define IDC_BUTTON_MAT_CONNECT_PRIS     1094
#define IDC_CHECK7                      1095
#define IDC_BUTTON_MAT_CONNECT_HEX      1095
#define IDC_CHECK8                      1096
#define IDC_EDIT_MSH_LINE               1096
#define IDC_CHECK9                      1097
#define IDC_EDIT_MSH_TRI                1097
#define IDC_EDIT_MSH_QUAD               1098
#define IDC_EDIT_MSH_TET                1099
#define IDC_CHECK12                     1100
#define IDC_EDIT_MSH_PRIS               1100
#define IDC_CROSSROADVEC                1100
#define IDC_CHECK13                     1101
#define IDC_EDIT_MSH_HEX                1101
#define IDC_CHECK14                     1102
#define IDC_EDIT_MSH_ELEMENTS           1102
#define IDC_CHECK15                     1103
#define IDC_EDIT_MSH_NODES              1103
#define IDC_CHECK16                     1104
#define IDC_LIST_MSH_MAT_GROUPS         1104
#define IDC_CHECK17                     1105
#define IDC_BUTTON_MAT_CONNECT          1105
#define IDC_LISTCTRL_POINT              1105
#define IDC_BUTTON_MAT_WRITE_TECPLOT    1106
#define IDC_LIST_TIMESTEP               1106
#define IDC_LIST_TIMESTEP2              1107
#define IDC_LIST_FCT                    1107
#define IDC_EDIT_MSH_NODES2             1107
#define IDC_TAB_METHOD                  1108
#define IDC_LIST_TIMESTEP3              1108
#define IDC_BUTTON_MSH_WRITE            1108
#define IDC_LIST_DOM                    1108
#define IDC_BUTTON_MSH_NAME             1109
#define IDC_BUTTON_MAT_CONNECT_THIS     1110
#define IDC_BUTTON_MAT_WRITE_TEC        1111
#define IDC_BUTTON_MAT_RESET            1112
#define IDC_BUTTON_MAT_CONNECT_LAYER    1113
#define IDC_LIST_WELL                   1114
#define IDC_BUTTON_MAT_CONNECT_FAILED   1114
#define IDC_DELETE                      1115
#define IDC_EDIT_MSH_NO_MAT             1115
#define IDC_EDIT_MSH_EDGE_MIN           1116
#define IDC_EDIT_MSH_ELEMENTS_DRAW      1116
#define IDC_EDIT_PLY_EPSILON            1117
#define IDC_EDIT_RATIO                  1119
#define IDC_EDIT_POWER                  1121
#define IDC_EDIT_SMOOTHING              1122
#define IDC_RADIO_DEFAULT               1123
#define IDC_EDIT_POWER_SLOPE            1123
#define IDC_RADIO_USERDEFINED           1124
#define IDC_LIST_VARIABLE               1126
#define IDC_BUTTON_ADVANCED             1127
#define IDC_COMBO_METHOD                1128
#define IDC_RADIO_USERDEFINED2          1129
#define IDC_RADIO_DEFAULT2              1130
#define IDC_COMBO_FUNCTION              1131
#define IDC_EDIT_RATIO2                 1132
#define IDC_EDIT_ANGLE2                 1133
#define IDC_EDIT_INTERVAL               1134
#define IDC_EDIT_LEVELS                 1134
#define IDC_RADIO_DEFAULT_KRIGING       1135
#define IDC_CHECK_NUGGET                1136
#define IDC_CHECK_TREND                 1137
#define IDC_COMBO_VARIO                 1138
#define IDC_EDIT_SILL                   1139
#define IDC_EDIT_RANGE                  1140
#define IDC_COMBO_TREND                 1141
#define IDC_RADIO_USERDEFINED_3         1142
#define IDC_STATIC_VARIO                1144
#define IDC_CHECK_LEGEND                1146
#define IDC_COMBO_PCS_H                 1147
#define IDC_COMBO_PCS_T                 1148
#define IDC_LIST_BC_NEW                 1148
#define IDC_COMBO_PCS_M                 1149
#define IDC_COMBO_PCS_TYPE              1149
#define IDC_COMBO_PCS_M2                1150
#define IDC_COMBO_PCS_C                 1150
#define IDC_COMBO_NOD_VALUES            1150
#define IDC_COMBO_VOL_SFC               1150
#define IDC_COMBO_TIM_UNIT              1150
#define IDC_COMBO_ELE_VALUES            1151
#define IDC_BUTTON_OUT_READ             1152
#define IDC_BUTTON_OUT_WRITE            1153
#define IDC_BUTTON_OUT_REMOVE           1154
#define IDC_BUTTON_OUT_CREATE           1155
#define IDC_LIST_OUT                    1156
#define IDC_TREE1                       1156
#define IDC_BUTTON_PCS_CREATE           1157
#define IDC_LIST_VOLUMES                1158
#define IDC_BUTTON_CLEAR                1158
#define IDC_BUTTON_CREATE_LAYER_VOLUMES 1159
#define IDC_BUTTON_VOLUMES_WRITE_TEC    1160
#define IDC_BUTTON_CLEAR_LIST           1161
#define IDC_PROGRESS1                   1162
#define IDC_PROGRESS_TINS               1162
#define IDC_CHECK_SIMULATOR1            1163
#define IDC_FILENAME                    1163
#define IDC_PROGRESS_MESH               1163
#define IDC_CHECK_SIMULATOR2            1164
#define IDC_FILEOPEN                    1164
#define IDC_CHECK_SIMULATOR3            1165
#define IDC_COMBO_TYPENAMES             1165
#define IDC_CHECK_DOUBLE_POINTS         1166
#define IDC_CHECK_SIMULATOR4            1166
#define IDC_GETVALUES                   1166
#define IDC_DELETE_DOUBLE_POINTS_BUTTON 1167
#define IDC_CHECK_SIMULATOR5            1167
#define IDC_CHOOSETEXT                  1167
#define IDC_CHECK_SIMULATOR6            1168
#define IDC_ANDTEXT                     1168
#define IDC_GET_MINMAXSEGLENGTH_BUTTON  1168
#define IDC_NEWNAME                     1168
#define IDC_CHECK_SIMULATOR7            1169
#define IDC_Z_IMAGEDISTORT              1169
#define IDC_CHECK_SIMULATOR8            1170
#define IDC_BUTTON2                     1170
#define IDC_LISTCONTROL_DATA            1170
#define IDC_BUTTON_NOT_DISTORT          1170
#define IDC_CHECK_SIMULATOR9            1171
#define IDC_CHECK1                      1171
#define IDC_BOUNDINGBOX_ON_OFF          1171
#define IDC_OK                          1171
#define IDC_NODE                        1171
#define IDC_SELECT_MODE                 1171
#define IDC_BOTHORONE                   1171
#define IDC_BUTTON6                     1171
#define IDC_CHECK_SIMULATOR10           1172
#define IDC_CANCEL                      1172
#define IDC_EDIT_POLYLINE_8             1172
#define IDC_COMBO_PCS                   1172
#define IDC_OGLMODE                     1172
#define IDC_SET_MINMAXSEGLENGTH_BUTTON  1172
#define IDC_ELEMENTNUMBERS_ON_OFF       1172
#define IDC_BUTTON7                     1172
#define IDC_CHECK10                     1172
#define IDC_CHECK_SIMULATOR11           1173
#define IDC_TYPENAMEDISPL               1173
#define IDC_MIN_EDIT                    1173
#define IDC_ELEMENT                     1173
#define IDC_EDIT_VOLUME_NAME            1173
#define IDC_COMBO_PCS2                  1173
#define IDC_COMBO_QUANTITIES            1173
#define IDC_GET_SEGLENGTH_SMALLER_DEF   1173
#define IDC_ELEMENTNUMBERS_ON_OFF2      1173
#define IDC_NODENUMBERS_ON_OFF          1173
#define IDC_BUTTON8                     1173
#define IDC_CHECK_MSH_H                 1173
#define IDC_CHECK_SIMULATOR12           1174
#define IDC_COMBO_MAT_PLY               1174
#define IDC_BOUNDARY                    1174
#define IDC_LIST_PCS                    1174
#define IDC_TRI2PRI_BUTTON              1174
#define IDC_BCNST                       1174
#define IDC_COMBO_MAT_GEO_TYPE          1174
#define IDC_COMBO_MAT                   1174
#define IDC_CHECK_SIMULATOR13           1175
#define IDC_COMBO_MAT_SFC               1175
#define IDC_PCS_NAME_EDIT               1175
#define IDC_ORIVIEW                     1175
#define IDC_BUTTON_PCS                  1175
#define IDC_LISTCTRL_POLYLINE           1175
#define IDC_QUAD2HEX_BUTTON             1175
#define IDC_NODEINDEX                   1175
#define IDC_CHECK_PCS_H                 1175
#define IDC_CHECK_SIMULATOR_READY       1176
#define IDC_SET_PCS_MINMAX_BUTTON       1176
#define IDC_DESELECT_MODE               1176
#define IDC_RADIO_TRIANGULATION         1176
#define IDC_PRI2TET_BUTTON              1176
#define IDC_EDIT_LAYERNUMBER            1176
#define IDC_TET2SURFACE_BUTTON          1176
#define IDC_COMBO_MAT_PROPERTIES        1176
#define IDC_CHECK_OBJ_H                 1176
#define IDC_BUTTON_RUN_SIMULATION       1177
#define IDC_LISTCONTROL_MMP             1177
#define IDC_MAX_EDIT                    1177
#define IDC_STOP_PICKING                1177
#define IDC_RADIO_QUADRILATERATIONIDC_RADIO_QUADRILATERATION 1177
#define IDC_HEX2PRI_BUTTON              1177
#define IDC_EDIT_LAYERTHICKNESS         1177
#define IDC_QUAD2TRI_BUTTON             1177
#define IDC_CHECK_EQS_H                 1177
#define IDC_COMBO_MAT_VOL               1178
#define IDC_GET_PCS_MINMAX_BUTTON2      1178
#define IDC_SELECTALL                   1178
#define IDC_LIST_PCS_SIM                1178
#define IDC_EDIT_MSH_DENSITY            1178
#define IDC_HEX2TET_BUTTON              1178
#define IDC_SET_PCS_MINMAX_BUTTON2      1178
#define IDC_CHECK_NOD_H                 1178
#define IDC_DESELECTALL                 1179
#define IDC_EDIT_MSH_DENSITY_I          1179
#define IDC_TRI_ANGLE_BUTTON            1179
#define IDC_BUTTON_GEO_MAT              1179
#define IDC_GET_PCS_MINMAX_BUTTON3      1179
#define IDC_CHECK_ELE_H                 1179
#define IDC_PICKEDLIST                  1180
#define IDC_EDIT_MSH_DENSITY_J          1180
#define IDC_TRI_LENGTH_BUTTON           1180
#define IDC_BUTTON_MAT_GEO_CLEAR        1180
#define IDC_UPDATEVALUE                 1181
#define IDC_LIST_SFC                    1181
#define IDC_TRI_AREAI_BUTTON            1181
#define IDC_SURFACES                    1182
#define IDC_LIST_SFC_MSH                1182
#define IDC_AUTOMATIC_MESH_DENSITY      1182
#define IDC_VOLUMES                     1183
#define IDC_COMBO_MMP                   1183
#define IDC_GEOMETRIC_MESH_DENSITY2     1183
#define IDC_SELECT_PLANE                1184
#define IDC_COMBO_MSP                   1184
#define IDC_GLOBAL_SPLIT_MESH_DENSITY3  1184
#define IDC_WRITEGLI                    1185
#define IDC_BUTTON_READ_DATA            1185
#define IDC_COMBO_MMP_GROUP             1185
#define IDC_START_GMSH_MESHING          1185
#define IDC_BUTTON_CREATE_GROUP         1186
#define IDC_COMBO_MFP                   1186
#define IDC_MSHNODES_IN_POLYGON         1186
#define IDC_COMBO_PCS_PV_NAME           1187
#define IDC_CLEAR_SELECTION             1187
#define IDC_EDIT_MSH_NAME               1188
#define IDC_MIN_MAX_EDGE_LENGTH         1188
#define IDC_COMBO_MFP_STD               1189
#define IDC_SELECT_ALL                  1189
#define IDC_BUTTON_CREATE_MFP           1190
#define IDC_SET_PATCH_INDEX             1190
#define IDC_BUTTON_WRITE_MFP            1191
#define IDC_GMSH_MSH_IMPORT             1191
#define IDC_BUTTON_FCT_CREATE           1192
#define IDC_TET_ANGLE_BUTTON            1192
#define IDC_BUTTON_FCT_REFRESH          1193
#define IDC_BUTTON_ST_READ              1193
#define IDC_TET_VOLUME_BUTTON           1193
#define IDC_BUTTON_ST_WRITE             1194
#define IDC_SET_MESHDENSITY             1194
#define IDC_BUTTON_ST_READ_DATA         1195
#define IDC_DELETE_LAST_MESH            1195
#define IDC_BUTTON_ST_WRITE_TEC         1196
#define IDC_PATCHINDEX_FOR_PLAINS       1196
#define IDC_BUTTON_ST_CREATE            1197
#define IDC_COMBINE_PATCHINDEX          1197
#define IDC_BUTTON_ST_CREATE_GROUP      1198
#define IDC_COMPRESS_PATCHINDEX2        1198
#define IDC_MERGE_MESHES                1199
#define IDC_CHECK2                      1200
#define IDC_UPDATE_ALL_VIEWS            1200
#define IDC_CHECK3                      1201
#define IDC_CHECKDOUBLENODES            1201
#define IDC_EDIT_NT                     1202
#define IDC_DELETEDOUBLENODES           1202
#define IDC_CHECK_MOD_T                 1202
#define IDC_EDIT_DT                     1203
#define IDC_SPLITELEMENTS               1203
#define IDC_CHECK_MOD_C                 1203
#define ID_ADD_TIME_STEPS               1204
#define IDC_MAPPING_RIGHT               1204
#define IDC_BUTTON_TIM_WRITE            1205
#define IDC_Y2Z                         1205
#define IDC_BUTTON_TIM_READ             1206
#define IDC_X2Y                         1206
#define IDC_BUTTON_TIM_REMOVE           1207
#define IDC_X2Z                         1207
#define IDC_BUTTON_TIM_CREATE           1208
#define IDC_CREATE_ELLIPSOID            1208
#define IDC_RADIO_BC_TYPE1              1209
#define IDC_EDIT_TIME_START             1209
#define IDC_LIST_VAL                    1209
#define IDC_NEW_MSH_FROM_MATMESH2       1209
#define IDC_NEW_MSH_FROM_MATMESH        1209
#define IDC_RADIO_BC_TYPE2              1210
#define IDC_EDIT_TIME_END               1210
#define IDC_EDIT_TIM_VALUE              1210
#define IDC_MSH_TEST_DELAUNAY3DLIB      1210
#define IDC_RADIO_BC_TYPE4              1211
#define IDC_LIST_VAL_ELE                1211
#define IDC_CREATE_ELLIPSE2D            1211
#define IDC_RADIO_BC_TYPE3              1212
#define IDC_RADIO_TIM_TYPE1             1212
#define IDC_MSHNODES_ALONG_POLYLINE     1212
#define IDC_BUTTON_OK                   1212
#define IDC_RADIO_BC_TYPE5              1213
#define IDC_RADIO_TIM_TYPE2             1213
#define IDC_MSH_TEST_DELAUNAY2DLIB      1213
#define ID_ADD_OUT_TIME                 1214
#define IDC_CREATE_ELLIPSE2D2           1214
#define IDC_CREATE_LINES_ALONG_POLYLINE 1214
#define IDC_RADIO_DAT_TYPE1             1215
#define IDC_RADIO_DAT_TYPE2             1216
#define IDC_UNSELECT                    1216
#define IDC_EDIT_X_Max                  1217
#define IDC_BUTTON_UPDATE_MD            1217
#define IDC_EDIT_BC_2                   1218
#define IDC_EDIT_Y_Max                  1218
#define IDC_BUTTON_DISTORT              1218
#define IDC_EDIT_MD                     1218
#define IDC_EDIT_BC_3                   1219
#define IDC_CHECK_TRIANGLE_MESH         1219
#define IDC_BUTTON4                     1219
#define IDC_BUTTON_CALC_PDMIN           1219
#define IDC_SFC_READ                    1219
#define IDC_EDIT_BC_4                   1220
#define IDC_EDIT_SQUARE_DELTA_Y         1220
#define IDC_BUTTON5                     1220
#define IDC_SFC_WRITE                   1220
#define IDC_EDIT_BC_5                   1221
#define IDC_EDIT_X_Min                  1221
#define IDC_LIST_MESH                   1221
#define IDC_EDIT_BC_6                   1222
#define IDC_EDIT_VALUE                  1222
#define IDC_EDIT_Y_Min                  1222
#define IDC_STRUC_2D_BUTTON             1222
#define IDC_EDIT_BC_7                   1223
#define IDC_EDIT_SQUARE_DELTA_X         1223
#define IDC_TRI_DELAUNAY_BUTTON         1223
#define IDC_EDIT_BC_8                   1224
#define IDC_CHECK_RECTANGLE_MESH        1224
#define IDC_CREATE_GEO_BOUNDINGBOX      1224
#define IDC_EDIT_BC_9                   1225
#define IDC_TRI_QUALITY_GRAPH_BUTTON    1225
#define IDC_EDIT_SLOPE_X                1225
#define IDC_RADIO_BC_TYPE6              1226
#define IDC_PTVALUE                     1226
#define IDC_COMBO_VOL_LAYER             1226
#define IDC_LIST1                       1226
#define IDC_ADD_POLYGON_BUTTON          1226
#define IDC_PATCH_INDEX                 1226
#define IDC_EDIT_SLOPE_Y                1226
#define IDC_LIST_STATIONDATA            1226
#define IDC_VELOCITYVECTOR              1227
#define IDC_COMBO_VOL_LAYER_SFC         1227
#define IDC_ADD_NEXT_POLYGON_BUTTON     1227
#define IDC_BUTTON_UNSELECTPOINT        1227
#define IDC_CHECK_ONLY_EQUI_TRI_MESH    1227
#define IDC_RADIO_BC_TYPE7              1228
#define IDC_NUMOFPARTICLES              1228
#define IDC_INOROUT                     1228
#define IDC_LIST_VOL_SFC                1228
#define IDC_RELOAD_GEO_BUTTON           1228
#define IDC_MESHDENSITY_INDEX           1228
#define IDC_COMBO_SFC_MSH_LAY           1228
#define IDC_COMBO_SHP_PNT               1228
#define IDC_POINT_READ                  1228
#define IDC_PICKEDINFO                  1229
#define IDC_LIST_VOL                    1229
#define IDC_EDITOR_GEO_BUTTON           1229
#define IDC_SHP_FILE                    1229
#define IDC_READPCT                     1229
#define IDC_POINT_WRITE                 1229
#define IDC_LIST_BC_POLYLINES           1230
#define IDC_LIST_GEO                    1230
#define IDC_SHOWPARTICLE                1230
#define IDC_BUTTON_VOL_CREATE           1230
#define IDC_POINT_NUMBERS_CHECK         1230
#define IDC_COMBO_SHP_PLY               1230
#define IDC_WRITE_POINT_TEC             1230
#define IDC_BUTTON_BC_ADD               1231
#define IDC_BUTTON_VOL_REMOVE           1231
#define IDC_GEO_EDITOR_BUTTON           1231
#define IDC_FILE_SHP                    1231
#define IDC_CINELE                      1231
#define IDC_LISTCTRL_POINTNEW           1231
#define IDC_BUTTON_BC_UPDATE            1232
#define IDC_BUTTON_VOL_READ             1232
#define IDC_MSH_EDITOR_BUTTON           1232
#define IDC_BUTTON_CREATE_PNT           1232
#define IDC_STATIC_MSH                  1232
#define IDC_BUTTON_BC_REMOVE            1233
#define IDC_BUTTON_VOL_WRITE            1233
#define IDC_MONTHCALENDAR1              1233
#define IDC_GEO_BASE                    1233
#define IDC_READ1                       1233
#define IDC_BUTTON_POLYLINE_WRITE       1233
#define IDC_BC_EDITOR_BUTTON            1233
#define IDC_BUTTON_BC_REMOVEALL         1234
#define IDC_BUTTON_VOL_WRITE_TEC        1234
#define IDC_TAB1                        1234
#define IDC_BUTTON_CREATE_PLY           1234
#define IDC_READ2                       1234
#define IDC_POLYLINE_UNSELECT           1234
#define IDC_GSP_EDITOR_BUTTON           1234
#define IDC_LIST_BC_QUANTITIES          1235
#define IDC_LIST_ST_POINTS              1235
#define IDC_LIST_PCS_TYPE               1235
#define IDC_COMBO_VOL_MSH               1235
#define IDC_BUTTON_CREATE_SFC           1235
#define IDC_SHOWALL                     1235
#define IDC_IC_EDITOR_BUTTON            1235
#define IDC_CHECK_If_Show_Iso           1235
#define IDC_NODBYPARTICLE               1235
#define IDC_LIST_BC_SURFACES            1236
#define IDC_LIST_TIM                    1236
#define IDC_COMBO_VOL_MAT               1236
#define IDC_BUTTON_CREATE_VOL           1236
#define IDC_CREATE                      1236
#define IDC_ELEFROMNODE                 1236
#define IDC_POLYLINE_REMOVEALL          1236
#define IDC_MCP_EDITOR_BUTTON           1236
#define IDC_EDIT_Num                    1236
#define IDC_RADIO_BC_TYPE8              1237
#define IDC_BUTTON_BC_CREATE_GROUP      1237
#define IDC_BUTTON_VOL_MAT              1237
#define IDC_LIST_MAT_GEO                1237
#define IDC_COMBO_GEO_PNT               1237
#define IDC_WRITE_MSH                   1237
#define IDC_ELEFROMEDGE                 1237
#define IDC_POLYLINE_REMOVE             1237
#define IDC_PCS_MAX_EDIT                1237
#define IDC_MMP_EDITOR_BUTTON           1237
#define IDC_STATIC_MinValue             1237
#define IDC_BUTTON_BC_ADD2              1238
#define IDC_EDIT_MAT                    1238
#define IDC_COMBO_GEO_PLY               1238
#define IDC_WRITE_MMP                   1238
#define IDC_PICKCROSSROADS              1238
#define IDC_POLYLINE_ADD                1238
#define IDC_PCS_MIN_EDIT                1238
#define IDC_MFP_EDITOR_BUTTON           1238
#define IDC_STATIC_Max_Value            1238
#define IDC_BUTTON_BC_REMOVE2           1239
#define IDC_BUTTON_BC_READ              1239
#define IDC_LIST_MAT_GEO_TYPE           1239
#define IDC_COMBO_GEO_SFC               1239
#define IDC_POLYLINE_ADD_LAYER          1239
#define IDC_VALUE_POINTS_BUTTON         1239
#define IDC_NUM_EDITOR_BUTTON           1239
#define IDC_Iso_Refresh                 1239
#define IDC_PICKPLANE                   1239
#define IDC_BUTTON_SELECTED_NODES       1240
#define IDC_COMBO_GEO_VOL               1240
#define IDC_COMBO_PLY_MSH               1240
#define IDC_OUT_EDITOR_BUTTON2          1240
#define IDC_Iso_AddListItem             1240
#define IDC_MSH                         1240
#define IDC_ISOLINE_ISOSURFACE_BUTTON   1240
#define IDC_LIST_BC                     1241
#define IDC_BUTTON_BC_WRITE             1241
#define IDC_GEO_NUMBER                  1241
#define IDC_TOXYPLANE                   1241
#define IDC_LISTCTRL_POLYLINENEW        1241
#define IDC_COMBO_PLY_MSH2              1241
#define IDC_SLIDER1                     1241
#define IDC_PCS_EDITOR_BUTTON           1241
#define IDC_LIST6                       1241
#define IDC_PERM                        1241
#define IDC_RADIO_UsingContourPlotCol   1241
#define IDC_BUTTON_FILEOPEN             1241
#define IDC_BUTTON_BC_READ_CSV          1242
#define IDC_BUTTON_GEO_WRITE            1242
#define IDC_LIST_MAT_GEO_FAKE           1242
#define IDC_SPARTICLE                   1242
#define IDC_SURFACE_ADD                 1242
#define IDC_SLIDER2                     1242
#define IDC_RFE_EDITOR_BUTTON           1242
#define IDC_Iso_DelListItem             1242
#define IDC_RADIO_Uniform               1242
#define IDC_TEXT_STATNAME               1242
#define IDC_BUTTON_BC_WRITE2            1243
#define IDC_BUTTON_WRITE_TEC            1243
#define IDC_SAVEASTXT                   1243
#define IDC_SURFACE_REMOVE              1243
#define IDC_ST_EDITOR_BUTTON            1243
#define IDC_ATBYPOLYLINE                1243
#define IDC_STATIC_MinValue2            1243
#define IDC_FILENAME_EDIT               1243
#define IDC_BUTTON_TIM                  1243
#define IDC_CREEP                       1243
#define IDC_SURFACE_REMOVEALL           1244
#define IDC_TIM_EDITOR_BUTTON           1244
#define IDC_Max                         1244
#define IDC_STATIC_Max_Value2           1244
#define IDC_TEXT_DATAFROMSTATION        1244
#define IDC_CHECK_PCS                   1244
#define ID_MSP_NEW                      1244
#define IDC_UNSELECT_SFC                1245
#define IDC_TEC_EDITOR_BUTTON           1245
#define IDC_Min                         1245
#define IDC_LIST7                       1245
#define IDC_EDIT_STATIONNAME            1245
#define IDC_CHECK_TIM                   1245
#define IDC_RADIO_METHOD                1245
#define ID_MSP_UPDATE                   1245
#define IDC_SURFACE_WRITE_TEC           1246
#define IDC_GEO_EDITOR_BUTTON2          1246
#define IDC_Step                        1246
#define IDC_SETPATCH                    1246
#define IDC_Iso_Refresh2                1246
#define IDC_BUTTON_STATDATA             1246
#define IDC_CHECK_NUM                   1246
#define IDC_RADIO_METHOD_2              1246
#define IDC_CREATE_SURFACE              1247
#define IDC_PATCHNO                     1247
#define IDC_Iso_AddListItem2            1247
#define IDC_CHECK_OUT                   1247
#define IDC_CHECK_PRECOND               1247
#define IDC_PLY2SFC                     1248
#define IDC_POUTSIDE                    1248
#define IDC_Iso_DelListItem2            1248
#define IDC_CHECK_BC                    1248
#define IDC_EDIT2                       1248
#define IDC_CREATE_LAYER_TINs           1249
#define IDC_PINSIDE                     1249
#define IDC_Iso_AddListItem3            1249
#define IDC_Iso_DeleteAll               1249
#define IDC_CHECK_IC                    1249
#define IDC_EDIT3                       1249
#define IDC_COMBO_MOD_H                 1249
#define IDC_COMBO_MSH_TIN               1250
#define IDC_PID                         1250
#define IDC_CHECK_ST                    1250
#define IDC_RADIO_METHOD_3              1250
#define IDC_CHECK_MOD_H                 1250
#define IDC_LIST_SFC_NEW                1251
#define IDC_CID                         1251
#define IDC_CHECK_MFP                   1251
#define IDC_RADIO_METHOD_4              1251
#define IDC_BUTTON_MOD_CREATE_H         1251
#define IDC_CHECK_MSP                   1252
#define IDC_EDIT4                       1252
#define IDC_BUTTON_MOD_RUN              1252
#define IDC_RADIO_METHOD_5              1253
#define IDC_BUTTON_MSH_EDITOR           1253
#define IDC_CHECK_MCP                   1254
#define IDC_RADIO_METHOD_6              1254
#define IDC_BUTTON_MOD_DELETE_H         1254
#define IDC_CHECK_MMP                   1255
#define IDC_RADIO_METHOD_7              1255
#define IDC_COMBO_MOD_M                 1255
#define IDC_CHECK_MOD                   1256
#define IDC_COMBO_MOD_T                 1256
#define IDC_COMBO_MOD_C                 1257
#define IDC_CHECK_MOD_M                 1258
#define IDC_EDIT_TS_1                   1301
#define IDC_EDIT_TS_2                   1302
#define IDC_EDIT_TS_3                   1303
#define IDC_EDIT_TS_4                   1304
#define IDC_EDIT_TS_5                   1305
#define IDC_LIST_TS                     1306
#define IDC_BUTTON_TS_1                 1307
#define IDC_BUTTON_TS_2                 1308
#define IDC_BUTTON_TS_3                 1309
#define IDC_BUTTON_TS_4                 1310
#define IDC_EDIT_TS_6                   1311
#define IDC_EDIT_GRAF_1                 1320
#define IDC_EDIT_GRAF_2                 1321
#define IDC_EDIT_GRAF_3                 1322
#define IDC_EDIT_GRAF_4                 1323
#define IDC_EDIT_UMIN                   1324
#define IDC_EDIT_UMAX                   1325
#define IDC_EDIT_GRAF_5                 1326
#define IDC_EDIT_GRAF_6                 1327
#define IDC_EDIT_PROJECT_NAME           1374
#define IDC_EDIT_PROJECT_NAME2          1375
#define IDC_EDIT_PROBLEM_TYPE           1375
#define IDC_EDIT_SIMULATOR1             1376
#define IDC_EDIT_SIMULATOR2             1377
#define IDC_EDIT_SIMULATOR3             1378
#define IDC_EDIT_SIMULATOR4             1379
#define IDC_EDIT_SIMULATOR5             1380
#define IDC_EDIT_SIMULATOR6             1381
#define IDC_EDIT_SIMULATOR7             1382
#define IDC_EDIT_SIMULATOR8             1383
#define IDC_EDIT_SIMULATOR9             1384
#define IDC_EDIT_SIMULATOR10            1385
#define IDC_EDIT_SIMULATOR11            1386
#define IDC_EDIT_SIMULATOR12            1387
#define IDC_EDIT_SIMULATOR13            1388
#define IDC_EDIT_NO1                    1389
#define IDC_EDIT_NO2                    1390
#define IDC_EDIT_NO3                    1391
#define IDC_EDIT_NO4                    1392
#define IDC_EDIT_NO5                    1393
#define IDC_EDIT_NO6                    1394
#define IDC_EDIT_NO7                    1395
#define IDC_EDIT_NO8                    1396
#define IDC_EDIT_NO9                    1397
#define IDC_EDIT_NO10                   1398
#define IDC_EDIT_NO11                   1399
#define IDC_EDIT_NO12                   1400
#define IDC_EDIT_NO13                   1401
#define IDC_EDIT_POLYLINE_1             1443
#define IDC_BUTTON_POLYLINE_ADD         1464
#define IDC_BUTTON_POLYLINE_UPDATE      1465
#define IDC_BUTTON_POLYLINE_REMOVE      1466
#define IDC_BUTTON_POLYLINE_REMOVEALL   1467
#define IDC_BUTTON_POLYLINE_PROPERTIES_ADD 1468
#define IDC_BUTTON_POLYLINE_PROPERTIES_UPDATE 1469
#define IDC_BUTTON_POLYLINE_PROPERTIES_REMOVE 1470
#define IDC_BUTTON_POLYLINE_PROPERTIES_REMOVEALL 1471
#define IDC_BUTTON_POLYLINE_PROPERTIES_UPDATEALL 1472
#define IDC_BUTTON_POLYLINE_ADD_LAYER   1473
#define IDC_BUTTON_POLYLINE_REMOVEALL2  1474
#define IDC_BUTTON_POLYLINE_WRITE_TEC   1474
#define IDC_BUTTON_POLYLINE_UNSELECT    1475
#define IDC_BUTTON_POLYLINE_READ        1476
#define IDC_BUTTON_POLYLINE_WRITETEC    1477
#define IDC_RADIO_MAT_FP_DENSITY1       1603
#define IDC_RADIO_MAT_FP_DENSITY2       1604
#define IDC_RADIO_MAT_FP_DENSITY3       1605
#define IDC_RADIO_MAT_FP_DENSITY4       1606
#define IDC_RADIO_MAT_FP_DENSITY5       1607
#define IDC_RADIO_MAT_FP_DENSITY6       1608
#define IDC_RADIO_MAT_FP_DENSITY7       1609
#define IDC_RADIO_MAT_FP_DENSITY8       1610
#define IDC_LIST_MAT_FP_DENSITY         1611
#define IDC_EDIT_MAT_FP_DENSITY_1       1612
#define IDC_EDIT_MAT_FP_DENSITY_2       1613
#define IDC_EDIT_MAT_FP_DENSITY_3       1614
#define IDC_EDIT_MAT_FP_DENSITY_4       1615
#define IDC_EDIT_MAT_FP_DENSITY_5       1616
#define IDC_COMBO1                      1618
#define IDC_EDIT_MAT_FP_DENSITY_6       1618
#define IDC_COMBO10                     1619
#define IDC_LIST_POLYLINES              1619
#define IDC_RADIO_MAT_FP_DENSITY9       1619
#define IDC_COMBO_MSH                   1619
#define IDC_COMBO_MAT_Lay               1619
#define IDC_COMCREEP                    1619
#define IDC_COMBO_PROCESS_PHASES        1620
#define IDC_LIST_POLYLINE               1620
#define IDC_EDIT_MAT_FP_DENSITY_7       1620
#define IDC_COMBO3                      1620
#define IDC_COMBO_GEO                   1620
#define IDC_COMBO_LAYER                 1620
#define IDC_COMBO4                      1621
#define IDC_EDIT_POLYLINE_2             1621
#define IDC_EDIT_MAT_FP_DENSITY_8       1621
#define IDC_LIST_POLYLINES2             1621
#define IDC_COMBO_MSH_NEW               1621
#define IDC_COMBO_PROCESS_COMP          1622
#define IDC_EDIT_POLYLINE_3             1622
#define IDC_EDIT_MAT_FP_DENSITY_9       1622
#define IDC_LIST_SURFACES2              1622
#define IDC_COMBO_GEO_LAYER             1622
#define IDC_COMBO6                      1623
#define IDC_EDIT_POLYLINE_4             1623
#define IDC_EDIT_MAT_FP_DENSITY_10      1623
#define IDC_LIST_SURFACES_MAP           1623
#define IDC_COMBO7                      1624
#define IDC_EDIT_POLYLINE_5             1624
#define IDC_COMBO2                      1625
#define IDC_EDIT_POLYLINE_6             1625
#define IDC_EDIT_MAT_FP_DENSITY_12      1625
#define IDC_COMBO_STATION               1625
#define IDC_COMBO8                      1626
#define IDC_EDIT_POLYLINE_7             1626
#define IDC_EDIT_MAT_FP_DENSITY_11      1626
#define IDC_COMBO_MCP                   1626
#define IDC_COMBO9                      1627
#define IDC_EDIT_POINTS                 1627
#define IDC_EDIT_POLYLINE_9             1627
#define IDC_EDIT_PDMIN                  1627
#define IDC_COMBO11                     1628
#define IDC_COMBO12                     1629
#define IDC_COMBO13                     1630
#define IDC_COMBO14                     1631
#define IDC_COMBO15                     1632
#define IDC_COMBO16                     1633
#define IDC_COMBO17                     1634
#define IDC_CHECK_PROCESS_H             1635
#define IDC_PLY_RADIO1                  1636
#define IDC_PLY_RADIO2                  1637
#define IDC_COMBO_MAT_FP_DENSITY        1637
#define IDC_PLY_RADIO3                  1638
#define IDC_PLY_RADIO4                  1639
#define IDC_PLY_RADIO5                  1640
#define IDD_CONTROL_FORM                2222
#define IDD_MSH_POLYLINES               2223
#define IDD_POLYLINE1                   2224
#define IDD_POLYLINE                    2224
#define IDD_PICKINGHANDLE               2225
#define IDD_MSH_SURFACES                2226
#define IDD_INITIAL_CONDITIONS          2227
#define IDD_MAT_MFP_EDITOR              2228
#define IDD_BOUNDARY_CONDITIONS1        2229
#define IDD_OUT                         2230
#define IDD_TIM                         2231
#define IDD_CONTROL_RIGHT_PICKING_FORM  2234
#define IDD_VOLUME_NEW                  2235
#define IDD_POINT_NEW                   2236
#define IDD_POLYLINE_NEW                2237
#define IDD_SURFACE_NEW                 2238
#define IDD_CONTROL_RIGHT_RESULTS       2241
#define IDD_CONTROL_RIGHT               2242
#define IDD_CONTROL_RIGHT_CAMERA        2243
#define IDD_CONTROL_RIGHT_TEMPLATE      2245
#define IDD_CONTROL_RIGHT_MESH          2246
#define IDD_CONTROL_RIGHT_GEO           2247
#define IDD_CONTROL_RIGHT_IMPORT_DATA   2248
#define IDD_CONTROL_RIGHT_PCS           2249
#define IDD_NUM_EDITOR                  2250
#define IDD_MOD_EDITOR                  2251
#define ID_HELP_OGLINFO                 32771
#define ID_BUTTON_DRAW                  32773
#define ID_CHANGE_SCENE                 32779
#define ID_ENVIR_LIGHTING               32789
#define ID_ENVIR_FLAT                   32790
#define ID_ENVIR_SMOOTH                 32791
#define ID_3DVIEW_EXAMPLES              32792
#define ID_EXAMPLES_STARTEXAMPLES       32795
#define ID_3DGLIVIEW_POINTS             32803
#define ID_3DGLIVIEW_LINES              32804
#define ID_3DGLIVIEW_POLYLINES          32805
#define ID_3DGLIVIEW_SURFACES           32806
#define ID_3DGLIVIEW_VOLUMES            32807
#define ID_3DGLIVIEW_POINTNUMBERS       32810
#define ID_GEOLIB_POLYLINES             32811
#define ID_MSHLIB_TRIANGULATION         32812
#define ID_MSHLIB_PRISGEN               32813
#define ID_MSHLIB_TETGEN                32814
#define ID_SIMULATOR_PROCESSES          32815
#define ID_SIMULATOR_TIMESTEPPING       32816
#define ID_SIMULATOR_NUMERICS           32817
#define ID_SIMULATOR_INITIALCONDITIONS  32818
#define ID_SIMULATOR_BOUNDARYCONDITIONS 32819
#define ID_SIMULATOR_SOURCETERMS        32820
#define ID_SIMULATOR_MATERIALS_FLUIDPROPERTIES_DENSITY 32821
#define ID_SIMULATOR_MATERIALS_FLUIDPROPERTIES_VISCOSITY 32822
#define ID_SIMULATOR_MATERIALS_SOLIDPROPERTIES 32823
#define ID_SIMULATOR_MATERIALS_MEDIUMPROPERTIES 32824
#define ID_SIMULATOR_MATERIALS_COMPONENTPROPERTIES 32825
#define ID_SIMULATOR_SOLVER             32826
#define ID_SIMULATOR_RUNSIMULATION      32827
#define ID_GRAPHICS_2D                  32828
#define ID_BUTTON32830                  32830
#define ID_3DVIEW_RFIVIEW               32831
#define ID_3DRFIVIEW_NODES              32834
#define ID_3DRFIVIEW_ELEMENTS           32835
#define ID_RFIVIEW_NODENUMBERS          32836
#define ID_RFIVIEW_ELEMENTNUMBERS       32837
#define ID_BUTTON32841                  32841
#define ID_GEOLIB_POINTS                32845
#define ID_MSHLIB_PRISGEN_MAPPING       32847
#define ID_MSHLIB_PRISGEN_VERTICALDISC  32848
#define ID_MSHLIB_PRISGEN_TRI2PRI       32850
#define ID_GEOLIB_SURFACES              32851
#define ID_FILE_SAVEAS                  32852
#define ID_OPEN_PROJECT                 32856
#define ID_OPEN_MSH                     32859
#define ID_OPEN_FEM                     32860
#define ID_OPEN_GEO                     32861
#define ID_SIMULATOR_SOURCE_TERM        32862
#define ID_MATERIAL_FLUID_DENSITY       32863
#define ID_FILE_EXPORT                  32864
#define ID_EXPORT_MSHFILE               32866
#define ID_EXPORT_FEMFILE               32867
#define ID_MSHLIB_REFINE                32868
#define ID_MATERIALS_VIEW               32870
#define ID_OUTPUT_OBERVATIONPOINTS      32872
#define ID_OBERVATIONPOINTS_OUTVIEW     32873
#define ID_OUT_OBERVATIONPOINTS         32875
#define ID_2DVIEW_OUT                   32879
#define ID_2DVIEW_OUTPROFILES           32880
#define ID_2DVIEW_OUTHORIZONTALSECTIONS 32881
#define ID_2DVIEW_OUTVERTICALSECTIONS   32882
#define ID_VIEW_TEMPORALPROFILES_CREATE 32885
#define ID_VIEW_TEMPORALPROFILES_PROPERTIES 32886
#define ID_SIMULATOR_FORWARD            32888
#define ID_OUTSPATIALPROFILES_CREATE    32889
#define ID_VIEW_SPATIALPROFILES_CREATE  32891
#define ID_VIEW_SPATIALPROFILES_PROPERTIES 32892
#define ID_2DVIEW_TIMTIMESTEPPING       32893
#define ID_TIMTIMESTEPPING_PROPERTIES   32895
#define ID_2DVIEW_NUMLINEARITERATIONS   32896
#define ID_2DVIEW_NUMNON                32897
#define ID_2DVIEW_MSHELEMENTQUALITY     32898
#define ID_2DVIEW_MAT                   32899
#define ID_VIEW_MAT_PROPERTIES          32903
#define ID_MSHLIB_LINEGEN               32907
#define ID_2DVIEW_MATGROUPS             32910
#define ID_VIEW_MAT_GROUPS_CREATE       32913
#define ID_VIEW_MAT_FUNCTIONS_CREATE    32915
#define ID_VIEW_MAT_GROUPS_PROPERTIES   32916
#define ID_2DVIEW_MSHVIEW               32917
#define ID_VIEW_MSH_CREATE              32923
#define ID_VIEW_MSH_PROPERTIES          32925
#define ID_MSHLIB_MAT_CONNECT           32926
#define ID_2DVIEW_GEOVIEW               32927
#define ID_VIEW_GEO_CREATE              32930
#define ID_VIEW_GEO_PROPERTIES          32931
#define ID_SOLIDPROPERTIES_DENSITY      32932
#define ID_SOLIDPROPERTIES_MATERIALPROPERTIES 32933
#define ID_SOLIDPROPERTIES_THERMALPROPERTIES 32934
#define ID_OUTPUT_GRAPHICSPROPERTIES    32935
#define ID_MSHLIB_QUADGEN               32939
#define ID_PRISGEN_DELETE               32940
#define ID_VIEW_ZOOMIN                  32941
#define ID_VIEW_ZOOMOUT                 32942
#define ID_VIEW_ZOOMFULL                32943
#define ID_MSHLIB_MSHEDITOR             32944
#define ID_FILE_ADDMEMBERTOPROJECT      32946
#define ID_FILE_REMOVEMEMBERFROMPROJECT 32950
#define ID_FILE_SAVEPROJECTMEMBER       32954
#define ID_ADD_GEO                      32958
#define ID_ADD_MSH                      32959
#define ID_ADD_FEM                      32960
#define ID_REMOVE_MSH                   32962
#define ID_REMOVE_FEM                   32963
#define ID_SAVEAS_GEO                   32964
#define ID_SAVEAS_MSH                   32965
#define ID_SAVEAS_FEM                   32966
#define ID_IMPORT_SHP                   32967
#define ID_EXPORT_TEC                   32968
#define ID_3DGLIVIEW_POLYLINENAMES      32971
#define ID_3DGLIVIEW_DOUBLEPOINTS       32972
#define ID_VIEW_FEM_PROPERTIES          32975
#define ID_VIEW_FEM_CREATE              32976
#define ID_IMPORT_RFO                   32977
#define ID_BUTTON_DRAW_POINT            32982
#define ID_VIEW_OUT2D_CREATE            32985
#define ID_VIEW_OUT2D_PROPERTIES        32986
#define ID_IMPORT_BMP                   32987
#define ID_OUTPUT_INTERPOLATION         32988
#define ID_INTERPOLATION_INVERSEDISTANCEWEIGHTING 32989
#define ID_INTERPOLATION_KRIGING        32990
#define ID_OUTPUT_INTERPOLATION32991    32991
#define ID_OUTPUT_EXPORTWELLS           32992
#define ID_TABLE_ATTRIBUTE              32993
#define ID_Menu32995                    32995
#define ID_VIEW_TIM_CREATE              32997
#define IDC_BACK_COLOUR                 32998
#define ID_3DVIEW_SPLITTEROGLCREATE     32999
#define ID_3DVIEW_OGLCREATE             33000
#define ID_3DGLIVIEW_ADDPOINTS          33001
#define ID_GEOLIB_DELETEDOUBLEPOINTS    33002
#define ID_MESHTEST_AREA                33003
#define ID_MESHTEST_ANGLE               33004
#define ID_MESHTEST_LENGTH              33005
#define ID_MESHTEST_AREA_GRAPH          33006
#define ID_MESHTEST_ANGLE_GRAPH         33007
#define ID_LIST_AREAQUALITY             33008
#define ID_LIST_ANGLEQUALITY            33009
#define ID_LIST_LENGTHQUALITY           33010
#define ID_MESHTEST_TETRA_VOLUME        33011
#define ID_MESHTEST_TETRA_ANGLE         33012
#define ID_MESHTEST_TETRA_VOLUME_GRAPH  33013
#define ID_MESHTEST_TETRA_TETRA_GRAPH   33014
#define ID_LIST_TETRAVOLUMEQUALITY      33015
#define ID_LIST_TETRAANGLEQUALITY       33016
#define IDM_NEW_GRAPH                   33017
#define ID_MESHGENERATOR_GMSH_TRIANGULATION 33018
#define ID_MSHLIB_MESHIMPROVEMENT       33019
#define ID_MESHTEST_LENGTH_GRAPH        33020
#define ID_Menu33022                    33022
#define ID_3DFEMVIEW_MODEL              33024
#define ID_IMPORT_EXCEL                 33025
#define ID_OUTPUT_POINTS                33026
#define ID_OUTPUT_POLYLINES             33027
#define ID_OUTPUT_SURFACES              33028
#define ID_OUTPUT_VOLUMES               33029
#define ID_OUTPUT_DOMAIN                33030
#define ID_GEOLIB_VOLUMES               33031
#define ID_LINEGEN_POLYLINES            33032
#define ID_LINEGEN_TRIANGLES            33033
#define ID_SIMULATOR_CHECKSTATUS        33034
#define ID_REMOVE_GEO                   33035
#define ID_MATGROUPS_EDITOR             33036
#define ID_DEM_ASC                      33038
#define ID_2DVIEW_FCTVIEW               33039
#define ID_VIEW_FCT_CREATE              33042
#define ID_VIEW_FCT_PROPERTIES          33043
#define ID_IMPORT_EXCEL_FCT             33045
#define ID_OPENGLVIEWFORPICKING_OPENUPOPENGLWINDOW 33046
#define ID_VIEWCONTROL                  33047
#define ID_OPENGLVIEWFORPICKING_PICKINGCONTROLPANEL 33048
#define ID_PICKEDPROPERTY               33049
#define ID_POLYLINE                     33051
#define ID_SURFACE                      33052
#define ID_VOLUME                       33053
#define ID_MSHLIB_HEXGEN                33054
#define ID_LINEGEN_QUADS                33055
#define ID_QUADGEN_POLYLINES            33056
#define ID_QUADGEN_SURFACES             33057
#define ID_MFP_EDITOR                   33059
#define ID_MSP_EDITOR                   33060
#define ID_MMP_EDITOR                   33061
#define ID_OUTPUT_EDITOR                33063
#define ID_PCSLIB_OUT                   33065
#define ID_POINT                        33067
#define ID_BUTTON33068                  33068
#define ID_MSH                          33068
#define ID_PCS                          33070
#define ID_MESHGENERATOR_DELAUNAY       33071
#define ID_SELECT                       33072
#define ID_DESELECT                     33073
#define ID_MATGROUP_POPUP_UPDATE        33073
#define ID_SELECTALL                    33074
#define ID_MATGROUP_POPUP_DELETE        33074
#define ID_DESELECTALL                  33075
#define ID_MESHGENERATOR_STRUCTURED2D   33076
#define ID_IMPORT_GMS                   33077
#define ID_GEO                          33078
#define ID_BUTTON33079                  33079
#define ID_CONTROL_PANEL                33079
#define ID_SHADING_COLOREDELEVATION     33080
#define ID_IMPORT_SHP_NEW               33082
#define ID_LINEGEN_SURFACE              33083
#define ID_RUN                          33084
#define ID_IMPORT_FLAC                  33085

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         33086
#define _APS_NEXT_CONTROL_VALUE         1259
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
