#!/bin/sh
sed 's/ATM/RTM/g' <int_atm.c >xxx
sed 's/atm/rtm/g' <xxx >int_rtm.c
sed 's/ATM/RTM/g' <int_atm.h >xxx
sed 's/atm/rtm/g' <xxx >int_rtm.h

sed 's/ATM/RTM/g' <cel_atm.c >xxx
sed 's/atm/rtm/g' <xxx >cel_rtm.c
sed 's/ATM/RTM/g' <cel_atm.h >xxx
sed 's/atm/rtm/g' <xxx >cel_rtm.h

sed 's/ATM/RTM/g' <cgs_atm.c >xxx
sed 's/atm/rtm/g' <xxx >cgs_rtm.c
sed 's/ATM/RTM/g' <cgs_atm.h >xxx
sed 's/atm/rtm/g' <xxx >cgs_rtm.h

more makekern
rm -f xxx

