# GeoSys - Makefile for LINUX
# Last modification 04/11/2004 WW
include ../sxc.mak 
include objects.mak

PARAM = -lm
.SUFFIXES: .o .cpp .h 
.cpp.o:
	$(C++)   $<
 dest: $(OBJS)
clean:; rm -rf *.o *.ti
